name: circular_widgets
description: Display widgets in a circle.
version: 3.0.0
homepage: https://github.com/Bdaya-Dev/circular-widgets
repository: https://github.com/Bdaya-Dev/circular-widgets

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

# dev_dependencies: 
flutter:
